apiVersion: v1

kind: Pod

metadata:
  name: my-pod
  labels:
    app: my-app

spec:
  containers:
    - name: my-container
      image: dhanvantarisoftware/dhanvantari-image
      ports:
        - name: my-container
          containerPort: 8080